#!/usr/bin/env bash

command_check="fix -v --dry-run"
command_fix="fix"
command=$command_check

if [ $# == 0 ]; then
  command=$command_fix
elif [ "$1" == "fix" ]; then
  command=$command_fix
elif [ "$1" == "check" ]; then
  command=$command_check
else
  echo "Specify a correct command [check, fix]";
  exit;
fi

COMPOSE_FILE="./docker/docker-compose.dev.yml"

docker-compose -f ${COMPOSE_FILE} exec -T php bash -c "./vendor/bin/php-cs-fixer $command"
